
apiVersion: v1
kind: Namespace
metadata:
  name: crawler
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: crawler
  name: crawler
  namespace: crawler
spec:
  type: NodePort
  ports:
    - port: 9527
      targetPort: 9527
      nodePort: 30053
  selector:
    k8s-app: crawler

---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: crawler
  name: crawler
  namespace: crawler
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: crawler
  template:
    metadata:
      labels:
        k8s-app: crawler
    spec:
      containers:
        - name: crawler
          image: "192.168.202.159:30003/library/crawler:0.1"
          imagePullPolicy: Always
          ports:
            - containerPort: 9527
              protocol: TCP


