---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapachephp
  name: myapachephp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapachephp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapachephp
    spec:
      containers:
      - image: cankush625/webpage
        name: webpage
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapachephpsvc
  name: myapachephpsvc
spec:
  ports:
  - nodePort: 30080
    port: 80 
    protocol: TCP
    targetPort: 80
  selector:
    app: myapachephpsvc
  type: NodePort
status:
  loadBalancer: {}

